service: slack-stickercommand
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  versionFunctions: false

  stage: prod
  region: eu-central-1
  logRetentionInDays: 14

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  lambda:
    handler: bin/lambda
    events:
      - httpApi:
          path: /command
          method: post
